[project]
name = "fitness"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.fit-tracker]
path = "contracts/fit-tracker.clar"
depends_on = []
